# Generated by Django 5.0.14 on 2025-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('starter', 'Starter'), ('premium', 'Premium'), ('pro', 'Pro')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='industry_category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('retail', 'Retail'), ('services', 'Services'), ('healthcare', 'Healthcare'), ('construction', 'Construction'), ('transport', 'Transport'), ('travel', 'Travel'), ('auto_repair', 'Auto Repair'), ('beauty', 'Beauty'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
