# Generated by Django 5.0.14 on 2025-10-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('sections', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.template'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='pages.page'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug',)},
        ),
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together={('page', 'order_index')},
        ),
    ]
