# Generated by Django 5.0.14 on 2025-10-25 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('view', 'View')], max_length=20)),
                ('resource_type', models.CharField(blank=True, choices=[('page', 'Page'), ('section', 'Section'), ('template', 'Template'), ('theme', 'Theme'), ('tenant', 'Tenant')], max_length=20)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
