# Generated by Django 5.0.14 on 2025-10-25 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', max_length=7)),
                ('font_family_heading', models.CharField(default='Inter', max_length=100)),
                ('font_family_body', models.CharField(default='Inter', max_length=100)),
                ('custom_css', models.TextField(blank=True)),
                ('theme_options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
