# Generated by Django 5.0.14 on 2025-10-25 09:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^jcw-[a-z]+-\\d+-[a-z]+\\d+$', 'Slug must follow format: jcw-{vertical}-{kit}-{type}{number} (e.g., jcw-rest-01-hero01)')])),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('nav', 'Navigation'), ('hero', 'Hero'), ('feature', 'Feature'), ('gallery', 'Gallery'), ('testimonial', 'Testimonial'), ('cta', 'Call to Action'), ('footer', 'Footer')], max_length=20)),
                ('vertical', models.CharField(max_length=10)),
                ('kit_number', models.CharField(max_length=5)),
                ('section_type_number', models.CharField(max_length=5)),
                ('framework', models.CharField(default='next', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('json_schema', models.JSONField(default=dict)),
                ('preview_image', models.ImageField(blank=True, upload_to='section_previews/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('compatibility_flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
