# Generated by Django 5.0.14 on 2025-10-25 09:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Slug must contain only lowercase letters, numbers, and hyphens')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website_type', models.CharField(choices=[('one_page', 'One Page'), ('multi_page', 'Multi Page'), ('ecommerce', 'eCommerce')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['website_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('placement_constraints', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
