# Generated by Django 5.0.14 on 2025-10-25 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0002_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatesection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
        migrations.AddField(
            model_name='templatesection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='templates.template'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('website_type', 'is_default')},
        ),
        migrations.AlterUniqueTogether(
            name='templatesection',
            unique_together={('template', 'order_index')},
        ),
    ]
