# Generated by Django 5.0.14 on 2025-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, choices=[('rest', 'Restaurant'), ('business', 'Business'), ('autorepair', 'Auto Repair'), ('portfolio', 'Portfolio'), ('ecommerce', 'E-commerce'), ('blog', 'Blog'), ('medical', 'Medical'), ('fitness', 'Fitness')], max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='css_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images/'),
        ),
        migrations.AddField(
            model_name='template',
            name='used_by_count',
            field=models.IntegerField(default=0),
        ),
    ]
