# Generated by Django 5.0.14 on 2025-10-25 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_template_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('website_type',), name='unique_default_per_website_type'),
        ),
    ]
